### ISSUE TITLE
Database not displaying when searched

### ISSUE THREAD

**Issue by mestill1** [wvulibraries/databases#26]
**Describe the bug**
From Helpdesk Ticket #20657:

I happened to notice that our new database, Roper Center, does not show up when I do a search in the Databases tab for "Roper". OnePetro (SPE) shows up, but not Roper Center.

**To Reproduce**
1. Go to databases page search box
2. Search for roper
3. Results list does not include "Roper Center"

**Expected behavior**

**Screenshots**

![FireShot Capture 039 - Databases - databases lib wvu edu](https://user-images.githubusercontent.com/43069962/72161522-44bf9400-338e-11ea-9663-ee8700ef9527.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by trmccormick** [comment]
This may have been a elasticSearch indexing issue that resolved itself. I checked today and it worked correctly.

![Screen Shot 2020-02-03 at 4 21 23 PM](https://user-images.githubusercontent.com/16909131/73691927-57816c00-46a1-11ea-8fa0-f742d132b61e.png)
