### ISSUE TITLE
HTML coding appears in database search results

### ISSUE THREAD

**Issue by mestill1** [wvulibraries/databases#27]
**Describe the bug**
When searching for databases, the HTML coding in the description appears.  

**To Reproduce**
1. Go to lib.wvu.edu
2. Click on "Databases" tab
3. Search "pubmed"  
4. Results show PubMed record but description shows HTML coding.  

**Expected behavior**
Database descriptions show up during searching the same as navigating by letter

**Screenshots**
![FireShot Capture 050 - Databases - databases lib wvu edu](https://user-images.githubusercontent.com/43069962/73291428-23540a00-41ce-11ea-8e58-8e27d1166d56.png)
![FireShot Capture 049 - Databases - databases lib wvu edu](https://user-images.githubusercontent.com/43069962/73291429-23eca080-41ce-11ea-8007-29f16044bc7d.png)
![FireShot Capture 048 - Libraries at West Virginia University - library wvu edu](https://user-images.githubusercontent.com/43069962/73291430-23eca080-41ce-11ea-8320-1d733365a56b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by trmccormick** [comment]
Update has been pushed to the server and is working correctly.
