### ISSUE TITLE
Keyword search not working correctly

### ISSUE THREAD

**Issue by mestill1** [wvulibraries/databases#28]
**Describe the bug**
Keywords added to a database are not bringing any search result.  I added "ulrich" and "ulrichs" to the database, Ulrichsweb, but they do not result any search results.  

**To Reproduce**
1. Go to lib.wvu.edu
2. Click on databases tab and search "ulrich"
3. See error of no results

**Expected behavior**
Should return "Ulrichsweb" as a search result when searching "ulrich" or "ulrichs"

**Screenshots**
![FireShot Capture 053 - Databases - databases lib wvu edu](https://user-images.githubusercontent.com/43069962/73389382-0b4dba80-42a2-11ea-91e1-e506e7b151c4.png)
![FireShot Capture 052 - Databases - databases lib wvu edu](https://user-images.githubusercontent.com/43069962/73389383-0b4dba80-42a2-11ea-9a8f-941d0a9458e7.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by trmccormick** [comment]
Update has been pushed to the server and is working correctly.
