### ISSUE TITLE
Tracking of Database Links 

### ISSUE THREAD

**Issue by ddavisgraphics** [wvulibraries/databases#58]
Tracking Databases

![Screen Shot 2021-02-15 at 1 27 16 PM](https://user-images.githubusercontent.com/4368305/107982734-97f11680-6f92-11eb-9ec6-4d939515b5f1.png)

![Screen Shot 2021-02-15 at 1 33 55 PM](https://user-images.githubusercontent.com/4368305/107982736-97f11680-6f92-11eb-992b-e78255787740.png)

**Comment by trmccormick** [comment]
Changes have been completed.
