### ISSUE TITLE
Curated Subjects are not Saving to Databases

### ISSUE THREAD

**Issue by mestill1** [wvulibraries/databases#9]
**Describe the bug**
When I try to add a "curated subject" to a database, it does not save.  The system says updated, but when I go back in edit, the curated subjects that I added are missing.  So far, I have experienced this with Compendex, and SciFinder Scholar databases.

**To Reproduce**
1. Go to any database.  
2. Click on any subject to add to "Curated Subjects"
3. Scroll down to save database edits. 
4. Click edit to go back into same database.
5. See error of subjects not saved.

**Expected behavior**
Subjects saved to "curated subjects" will show up with yellow box on subject landing page.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser CHROME

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ddavisgraphics** [comment]
Hi Matt, sorry I've been on vacation, but I will look at this ASAP.

**Comment by mestill1** [comment]
Dave,  I am still not able to save those curated subjects.  I tested Compendex and SciFinder Scholar again.  Thanks.

**Comment by ddavisgraphics** [comment]
Matt.  I'll look again.  I think what has happened is the code hasn't been pushed to the production server yet.  We are doing a merge soon of some other behaviors and will get this fixed ASAP.

**Comment by ddavisgraphics** [comment]
I'll let you know when it is in production.

**Comment by ddavisgraphics** [comment]
This is working in production now.
